### ISSUE TITLE
Deprecation warning appear after upgrade from ember-cli 2.5.1 to 2.6.2

### ISSUE THREAD

**Issue by albertonavarro087** [ciena-frost/ember-frost-core#127]
> DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super(), addon: `ember-frost-core`

this error doesn't not allow to upgrade to latest ember-cli version

please see this issue [Unable to run `ember init` after upgrading to 2.6.0](https://github.com/ember-cli/ember-cli/issues/5973) from ember-cli repository

thank you

**Comment by sglanzer-fire** [comment]
We're working on a mass fix across our repos for this, should be ready shortly - thanks for the heads up!

**Comment by rox163** [comment]
Fixed via this commit - https://github.com/ciena-frost/ember-frost-core/commit/74677b453b8ea7e42776ae8ac3d8120d81f70d10
