### ISSUE TITLE
version mismatch in ember-cli-sass

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-core#161]
Currently, an `npm install` of `ember-cli-sass` reports version 5.5.0 which does not exist.

Pin the `ember-cli-sass` version to 5.4.0 in package.json until this issue is resolved.

**Comment by sandersky** [comment]
Well technically the npm version exists but it is missing all of the source code http://registry.npmjs.org/ember-cli-sass/-/ember-cli-sass-5.5.0.tgz. But I agree for now the solution is to pin to `5.4.0` or more explicitly I've begun pinning it with the following `>=5.1.0 <= 5.4.0`.

**Comment by juwara0** [comment]
https://github.com/aexmachina/ember-cli-sass/issues/131
