### ISSUE TITLE
The button jump when its clicked

### ISSUE THREAD

**Issue by baconC** [ciena-frost/ember-frost-core#181]
Can be fixed by adding border transparent and background clip

.frost-button.primary {
    background: linear-gradient(#37bbff,#009EEF);
    color: #FFF;
    border: 2px solid transparent;
    border-radius: 4px;
    -moz-background-clip: padding;
    -webkit-background-clip: padding;
    background-clip: padding-box;
}

.frost-button.primary:hover:not(.disabled) {
    background: #43C9F7;
    -moz-background-clip: padding;
    -webkit-background-clip: padding;
    background-clip: padding-box;
}

**Comment by sglanzer-fire** [comment]
Fixed in #408
