### ISSUE TITLE
frost-toggle-button: Create test suite

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-core#194]
Create the unit and integration test suite for frost-toggle-button:

https://github.com/ciena-frost/ember-frost-core/pull/149#event-803024382

**Comment by juwara0** [comment]
We need to create the README. Right now there is not a README for frost-toggle in docs/

I have made the link in the main README point to docs/frost-toggle.md

**Comment by dafortin** [comment]
I will add hooks as in #269

**Comment by juwara0** [comment]
Closed via: https://github.com/ciena-frost/ember-frost-core/pull/276
