### ISSUE TITLE
Create a utility to simplify the validation of the fct

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-core#259]
* Check if the fct is set
* Check if it's a fct
* log an error if it's not an fct
* otherwise call the fct

**Comment by sglanzer-fire** [comment]
What's an `fct`?

**Comment by dafortin** [comment]
Function

**Comment by sglanzer-fire** [comment]
Ahhhh, this is referring to the checks for an action set against an event handler - still useful for optional cases, but I think I'd be happy with just an `if` at this stage - JS will yell if it's not a function

**Comment by job13er** [comment]
With prop-types and default values, you don't even need the `if`, you can just default to an empty function and then you know you can call it. Also, prop-types will yell too if it's not a function.

**Comment by sglanzer-fire** [comment]
Sure, a default no-op would be fine as well
