### ISSUE TITLE
Overrided default ember g component generation

### ISSUE THREAD

**Issue by albertonavarro087** [ciena-frost/ember-frost-core#272]
I saw in the latest versions, 0.32.2, that `ember g component ` is been overrided but I found this PR https://github.com/ciena-frost/ember-frost-core/pull/170 where there is an indication to  use frost-component instead to avoid override default component blueprint

Is this suppose to happen in that way?

**Comment by sglanzer-fire** [comment]
@job13er ^

**Comment by sglanzer-fire** [comment]
There should be an opt-out flag for this

**Comment by job13er** [comment]
Why do we want an opt-out flag? When is it better to use the ember component?

**Comment by sglanzer-fire** [comment]
Non-Ciena consumers - it's cheap to do and makes it easier for other people - no rush, but it's not a bad idea

**Comment by job13er** [comment]
There are non-ciena consumers? I don't mind if someone else wants to add it, but it's certainly not high on my priorities to change. I'm actually interested in trying alternatives to `ember-cli` so I'd probably not be using `ember g ` anymore soon anyway.

**Comment by sglanzer-fire** [comment]
Yeah, I wasn't suggesting that you would need to do this, just something on the general list

**Comment by job13er** [comment]
Moved to https://github.com/ciena-frost/ember-cli-frost-blueprints/issues/9
