### ISSUE TITLE
frost-toggle: UX design spec lists `hover` color - needs implementation

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-core#301]
The UX design spec lists `hover` color as a visual feature of frost-toggle. This is currently not implemented.

**Comment by jscharf** [comment]
I've opened PR https://github.com/ciena-frost/ember-frost-core/pull/466 that includes the implementation for the hover color in frost-toggle.

**Comment by jscharf** [comment]
PR #466 has has been merged so this issue can be closed.
