### ISSUE TITLE
Fix acceptance tests to avoid them to stuck during execution

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-core#327]
We currently have a skip against the acceptances tests because they were causing issues during the execution of the tests.

The tests were running successfully but they were getting stuck and avoiding the completion of the run.
Note: might be related to code coverage.

**Comment by sglanzer-fire** [comment]
Fixed in https://github.com/ciena-frost/ember-frost-core/pull/337/files#diff-f110515e6af13dcf2214d5f28da950a0R6 thanks to @rox163
