### ISSUE TITLE
Initialization values of `null` cause prop-type warnings in the console of the demo app

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-core#364]
Initializing a component property to a value of `null` with a type set in propTypes causes a warning to be shown in the console of the dummy app.

For example:

```
propTypes: {
  title: PropTypes.string
},

getDefaultProps () {
  return {
    title: null
  }
}
```

We need to update propTypes in these cases like so:

```
propTypes: {
  title: PropTypes.oneOfType([
    PropTypes.null,
    PropTypes.string
  ])
},

getDefaultProps () {
  return {
    title: null
  }
}
```

**Comment by juwara0** [comment]
In the case of https://github.com/ciena-frost/ember-frost-core/pull/363/files#diff-8a0114752a33a261655def2de4c92f62 (addon/components/frost-password.js) there were property values being set to null and they were removed instead of making the update above. These will need to be added back in and updated as shown above.

The tests for those properties were removed and need to be added back in as well: https://github.com/ciena-frost/ember-frost-core/pull/363/files#diff-d9d7ae7b46c8f7c9acfa2dceefabd861

**Comment by sglanzer-fire** [comment]
What's the point of the `null` default?  Defaults are meant to provide an initial non-null value, since anything not given a default will implicitly be null (or undefined)

**Comment by job13er** [comment]
Unless `null` has some semantic meaning that differs from `underfined` in the context of the component, I think it is a much better idea to leave it as `undefined`

**Comment by juwara0** [comment]
I am closing this issue after thinking about this some more. I have come to the conclusion that a key differentiator in our approach here at Ciena is the use of `ember-prop-types`.

**Comment by sglanzer-fire** [comment]
I think that's a solid assessment, thanks for the discussion @juwara0
