### ISSUE TITLE
Create async test helpers for frost-select

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-core#385]
**PROBLEM:** When a `frost-select` component is rendered it is not immediately available in the DOM in order to perform `find(hook('facets-name')).find('svg').click()` or similar.

**PROBLEM:** When items are being rendered in a `frost-select` that are being loaded from an async data call there is (can be) a delay in their rendering. In an acceptance test this delay causes problems because when attempting to interact with these items they are not yet rendered and the test will fail.

**SOLUTIONS:**

* An async test helper should be created and exported as part of of this repo that will resolve its promise
  * when the control is available in the DOM.
  * when all of the items have been retrieved and are available in the DOM.

**Comment by sandersky** [comment]
Regarding, "when all of the items have been retrieved and are available in the DOM", how would the test helper know that? It is up to the consumer to retrieve items, the select component is just a dumb renderer (knows nothing about fetching data). I however do agree interacting with the select in tests is still sub-par, given you have to call `.trigger('mousedown')` instead of `.click()` to open it.

**Comment by notmessenger** [comment]
The dumb renderer may need to be made a little smarter so that it's aware of how many items it is rendering and then notify when it is complete.  `didInsertElement()` is called from the inside-out so it would be pretty easy to track this.  The async helper can then tie into this state.

Some very rough pseudo-code to illustrate:

```

// application template

{{frost-select
  data=model
  isRendered=(action ???)
}}

// frost-select component

{
  hasEverythingBeenRendered: false,

  howManyHaveBeenInserted: 0

  actions: {
    wasInserted() {
      howManyHaveBeenInserted++
    }
  }

  didInsertElement() {
    if (data.count === howManyHaveBeenInserted) {
      this.get('isRendered')()
    }
  }
}

// frost-select template

{{#each option as |option|}}
  {{frost-select-option
    option=option
    onDidInsert=(action 'wasInserted')
  }}
}}


// frost-select-option component

{
  didInsertElement() {
    this.get('onDidInsert')()
  }
}
```

**Comment by sandersky** [comment]
The select is aware of how many items it is rendering in the sense it can look at the length of the data. It doesn't try and predict how many items it may be rendering at some point in the future (such as when the consumer is feeding it API driven data). Of course in that case it'd be hard to know that length until after the data is fetched, at which point you'd be rendering it anyways.

**Comment by notmessenger** [comment]
There are certainly some logistics and architecture that need to be thought about but the initial two problems I listed are ones that are currently being encountered due to rendering delays.  I want to make sure that even if this conversation has arrived at a coding solution that it remains recognized that a solution is needed, even if it's a rethink of how to approach this problem in an acceptance test.

**Comment by sandersky** [comment]
While I'm not sure it quite does whatever it is you are looking for I added two new test helpers in this [pull request](https://github.com/ciena-frost/ember-frost-core/pull/386) and an example to make it a little easier to work with the select in tests.

**Comment by notmessenger** [comment]
The diff below resulted in this issue no longer being applicable.  I suspect (but have not yet confirmed) that the async helpers have a "wait until the DOM has been rendered" sort of approach because all the that changed below was instead of calling a few synchronous calls they were changed to async ones.  But they both both begin immediately with searching the DOM for an element and not following any other event.

Now that I'm thinking about it some more (and still have not confirmed) the async helpers likely are scheduled to run after render.

```
       it('selecting an item updates query parameters', function () {
-        // @todo Refactor after https://github.com/ciena-frost/ember-frost-core/issues/385 is resolved
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-
-        find(hook('facets-name')).find('svg').click()
-
-        // @todo Refactor after https://github.com/ciena-frost/ember-frost-core/issues/385 is resolved
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-        $hook('search-input').click()
-
-        $hook('facets-name-item', {label: 'TestNode13'}).trigger('mousedown')
+        click(hook('facets-name') + ' > svg')
+        triggerEvent(
+          hook('facets-name-item', {label: 'TestNode13'}),
+          'mousedown'
+        )
```
