### ISSUE TITLE
Frost select performance

### ISSUE THREAD

**Issue by TheOtherDude** [ciena-frost/ember-frost-core#398]
I have a frost-select in my app with 200 options.

Currently, the click to open it takes about 330 ms with `1.7.6` and over 900 ms with `1.9.0`. On other machines, we have timed it at over 3.25 seconds with `1.9.0`.

Something added between `1.7.6` and `1.9.0` is really killing frost-select performance.

**Comment by srowhani** [comment]
Maybe we can look into using smoke-and-mirrors in the `select-dropdown`

**Comment by TheOtherDude** [comment]
This issue was resolved by PR #400, #402, #403, and #404.
