### ISSUE TITLE
`frost-icon` flickers when re-rendering the containing component

### ISSUE THREAD

**Issue by sglanzer-fire** [ciena-frost/ember-frost-core#410]
Let’s say you have a simple component or view, just a record with an icon and some text.  User updates a value, causing a `this.set` to re-render that view.  That icon will blink, even though it hasn’t been changed.

**Comment by sglanzer-fire** [comment]
Would make sense to take a second look at the `#use` mechanics - potentially steal some ideas from `ember-svg-jar`

**Comment by srowhani** [comment]
https://github.com/ciena-frost/ember-frost-sort/pull/59/files
