### ISSUE TITLE
Add debounce to `select` when user is typing

### ISSUE THREAD

**Issue by d-ashfield** [ciena-frost/ember-frost-core#411]
Would be nice to have a debounce when the user is typing, especially when a server api is invoked, so that it's not going off to query on every character entered.

**Comment by srowhani** [comment]
Would the debounce be better suited inside of frost-select or inside the `onInput` hook passed into `frost-select`? @sglanzer.

**Comment by sglanzer-fire** [comment]
@srowhani this is for the `query` case, which I believe is exclusive to bunsen, but yes it would need to be in the handler of the `onInput` in that code

**Comment by sandersky** [comment]
I think it is worth adding a boolean property so you can do something like `debounce=true`. When set the select will debounce the input to wait until the user stops typing before triggering onInput.

**Comment by job13er** [comment]
If you're going to make a parameter, probably better to be a number instead of a boolean, so one can control how much of a debounce is used.

**Comment by sglanzer-fire** [comment]
`inputDebounce=200`?

**Comment by job13er** [comment]
I was thinking maybe `debounceInterval=200` or `debouncePeriod=200` I think it's inferred that you'd be denouncing the user input. Not sure what else would need to be denounced for a select component.

**Comment by sandersky** [comment]
I think `debounceInterval` or `debounceDuration` sounds good.

**Comment by sglanzer-fire** [comment]
I like `debounceInterval`
