### ISSUE TITLE
When users add sorts, it should open up the drop down list. 

### ISSUE THREAD

**Issue by baconC** [ciena-frost/ember-frost-core#414]
![image](https://cloud.githubusercontent.com/assets/17321686/23570888/5d2a1cd0-0034-11e7-81a0-8871dc50bfde.png)

Currently it just pick the first item from the sortable item .

**Comment by sglanzer-fire** [comment]
Need to move this to `ember-frost-sort`

**Comment by baconC** [comment]
OK, done
