### ISSUE TITLE
Refactor test-support/ content to addon-test-support/

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-core#446]
In the next major, we should move the helpers we have in `test-support/` to the more appropriate `addon-test-support/`. Like we did for `ember-test-utils` [here](https://github.com/ciena-blueplanet/ember-test-utils/pull/48)

**Comment by juwara0** [comment]
Closed via: https://github.com/ciena-frost/ember-frost-core/pull/540
