### ISSUE TITLE
Invalid regular expression when searching in multi-select

### ISSUE THREAD

**Issue by frosetti** [ciena-frost/ember-frost-core#455]
Searching for "**e2e_template_forrest1 (For**" in a multi-select renderer via bunsen causes this error in the browser.

vendor-400223a01e0a7550756812779bce20bb.js:102 Uncaught SyntaxError: Invalid regular expression: /e2e_template_forrest1 (/: Unterminated group
    at RegExp (<anonymous>)

**Comment by sglanzer-fire** [comment]
I take it the `(` is causing issues

**Comment by frosetti** [comment]
Yes, just verified typing "**(**" in the search field causes:
"_Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group_"
