### ISSUE TITLE
Button demo for Design: info-bar style references non-existent search icon

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-core#494]
Visit http://ciena-frost.github.io/ember-frost-core/#/button to view the bug. 

The section underneath he heading Design: info-bar contains two buttons. Each button has text on it but no icon. If you look at the reference code below the buttons, they each have a `icon='search'` property in the example template code. There is no search icon in ember-frost-core anymore, so no icon appears in the demo.

**Comment by rox163** [comment]
@jscharf could you please just replace that icon with something else like the Add and then close this issue?
