### ISSUE TITLE
frost-scroll needs a mechanism to refresh the scroll aside from using actual scroll up/down

### ISSUE THREAD

**Issue by helrac** [ciena-frost/ember-frost-core#496]
The issue i'm encountering is when using ember-frost-object-browser where i have a list of filters and the screen size is smaller than the list, when i go to scroll using the mouse with only clicks the scrollbar isn't there.

**Comment by rox163** [comment]
not sure Im clear on the issue here. is this something that maybe we need to fix in object browser? You can use the scrollTop() function if you need to reset a scroll view anywhere..

**Comment by helrac** [comment]
The issue is that there is no scrollbar at all because the rendering of contents inside of the scroll is rendered after. In this case there is no scrollbar even though there should be one since the viewing area is smaller than the screen. scrollTop() may do this as well, but I was adding an option in frost-scroll for a flag where it will add a mouseenter event to run window.Ps.update(element) to add/remove/update (update not so much) scrollbars. in the object-browser i would just pass in the parameter of true for this option.

**Comment by rox163** [comment]
#497
