### ISSUE TITLE
Disabled frost-buttons do not show their title

### ISSUE THREAD

**Issue by TheOtherDude** [ciena-frost/ember-frost-core#523]
The frost-button `disabled` class applies `pointer-events: none;`, but that prevents tooltips from showing. I believe `cursor: default;` would achieve the desired effect without breaking title tooltips.

**Comment by notmessenger** [comment]
I'm assuming that we want to show tooltips for disabled buttons?  Tooltips are normally additive instructional information, which is not relevant in the case of the button being disabled.  I'm fine either way, just asking if we have direction from UX on this (I have not specifically ran across this but am not fully familiar with all of the UX material yet).

**Comment by TheOtherDude** [comment]
Correct, we use tooltips to tell the user why a button is disabled in cases where it's not obvious. This is under UX direction from Katie Parmeson.
