### ISSUE TITLE
On fresh addon get `Could not find module `ember-hook` imported from `ember-frost-core/components/frost-component``

### ISSUE THREAD

**Issue by EWhite613** [ciena-frost/ember-frost-core#524]
When doing an install of `ember-frost-core` on a new addon you get:
`Could not find module 'ember-hook' imported from 'ember-frost-core/components/frost-component'`
Looks like it was removed from blueprint but not added to dependencies

### Workaround
`ember install ember-hook`

**Comment by notmessenger** [comment]
Yeah, `ember-hook` is normally a devDependency, used only in the test environment.  However, due to our usage of it to build up hook names/values for consumption in the test environment it in fact needs to be a dependency and I messed that up when I addressed #520.   I have opened a PR to fix this.

**Comment by notmessenger** [comment]
JIRA: FROST-639
