### ISSUE TITLE
Add label component prop and click chevron only prop for frost-expand

### ISSUE THREAD

**Issue by anhuynh** [ciena-frost/ember-frost-core#555]
# FEATURE REQUEST / CODE CHANGE

## Summary
Add two new optional props to the `frost-expand` component: a prop that makes the chevron the only clickable area to expand/collapse and a prop that uses a component in the label instead of just a plain string.

## Motivation
* Describe the big picture of your feature to communicate why it should be added.
  * Why are we doing this?
So that there are additional options to match UX specs when using `frost-expand` to build other components
  * What use cases does it support?
Additional behaviour and aesthetic options for consumers
  * What is the expected outcome?

## Detailed design

The `isChevronOnlyClickTrigger` prop when `true` will make the chevron icon the only clickable area to expand or collapse instead of having the entire label be clickable. The `onClick` action on the label and chevron will be conditional dependent on the `isChevronOnlyClickTrigger` prop.

When the `labelComponent` is passed in with a component, it will be displayed instead of the expand/collapse string labels. An additional `if` statement can be added in the `frost-expand` template to support showing the `labelComponent`.

## How we teach this

* What names and terminology work best for these concepts and why?
`labelComponent` is self explanatory.
`isChevronOnlyClickTrigger` is self explanatory but may be a bit too long.
* How should this feature be introduced and taught to existing users?
It will be added to the dummy app and any documentation for `frost-expand`

## Drawbacks

I don't think there are any since these are optional props

**Comment by notmessenger** [comment]
> Detailed design
The `onClick` action on the label and chevron will be conditional dependent on the `isChevronOnlyClickTrigger` prop

Do you mean that the `onClick` action will still be called for whichever one of these is designated as the clickable area?

**Comment by notmessenger** [comment]
> Detailed design
When the `labelComponent` is passed in with a component, it will be displayed instead of the expand/collapse string labels.

When employed when `isChevronOnlyClickTrigger` is false will the entire component container be clickable, regardless of the content inside?  Otherwise how are you planning on targeting specific content from the rendered component as only being clickable?

**Comment by notmessenger** [comment]
> How we teach this
How should this feature be introduced and taught to existing users?
It will be added to the dummy app and any documentation for `frost-expand`

A _frost-expand.md_ document should be added to https://github.com/ciena-frost/ember-frost-core/tree/master/docs

**Comment by anhuynh** [comment]
> Do you mean that the onClick action will still be called for whichever one of these is designated as the clickable area?

The `onClick` action will only be called in whichever is the designated clickable area.

> When employed when isChevronOnlyClickTrigger is false will the entire component container be clickable, regardless of the content inside? Otherwise how are you planning on targeting specific content from the rendered component as only being clickable?

When `isChevronOnlyClickTrigger` is false or not specified, the label portion of `frost-expand` which includes `labelComponent` will be clickable. The action on the entire label portion will be conditional so that we can target other things instead like just the chevron
