### ISSUE TITLE
Button's onclick event needs only controller?

### ISSUE THREAD

**Issue by ChangJoo-Park** [ciena-frost/ember-frost-core#70]
Hello, I use button with action, but I don't have any controller
everytime I use buttons, create controller?

**Comment by gknoy** [comment]
@ChangJoo-Park: If you are using an **Ember 2.0** component ([as described in these docs](https://guides.emberjs.com/v2.5.0/components/triggering-changes-with-actions/)), you do not need to define a controller for the component.  You should be able to do:

``` javascript
// foo-component/component.js

export default Ember.Component.extend({
  // ....
  actions: {
    doSomething: function () {
      console.log('doSomething was called')
    }
  }
})
```

``` hbs
{{! foo-component/template.hbs }}
{{frost-button
  onClick=(action "doSomething")
  priority="primary"
  size="medium"
  text="Do Something"
}}
```

If you're invoking the `{{frost-button ... }}` in the template of a **route**, you will need to define the action handler in your route's controller.

**Comment by rox163** [comment]
this doesnt look like a bug...more of concept clarification. Closing
