### ISSUE TITLE
Search icon missing handle of magnifying glass

### ISSUE THREAD

**Issue by sandersky** [ciena-frost/ember-frost-core#75]

**Comment by vesper2000** [comment]
@sandersky Where are you seeing this issue?  I checked the icons demo and button and it looks fine to me.

**Comment by sandersky** [comment]
I see it in the demo with Google Chrome Version 50.0.2661.86 (64-bit) on OS X 10.10.5. Below is a screenshot of what I'm seeing. I also see the same thing with Safari and Firefox.

<img width="132" alt="screen shot 2016-04-25 at 10 53 53 am" src="https://cloud.githubusercontent.com/assets/422902/14793451/1b18330a-0ad4-11e6-931b-f7e4f37056ab.png">

I'd suspect that icon should look more like https://cdn1.iconfinder.com/data/icons/user-interface-elements/154/search-loop-512.png with the line coming off of the circle as the magnifying glass handle.
