### ISSUE TITLE
frost-select: popup display location needs to be smarter

### ISSUE THREAD

**Issue by TheAxeMan301** [ciena-frost/ember-frost-core#99]
Currently when you open up a select or multi-select box the list is always below the entry. Furthermore, there is no logic to prevent the box from getting cut off on the bottom of the screen.

There are a few different schemes that can ensure the contents are always visible. A simple one is to just  move the window up so the bottom never goes past the end of the screen. A good example I noticed is the window that comes up in gmail giving you different actions you can take on a message. Even though the window scrolls the display avoids cutting the window off. If it is possible that someone would want the window location fixed below we could add a property for that.

Also is there any logic for the window height to stop growing and switch to scrollbars for larger numbers of items? I want that too.

**Comment by sandersky** [comment]
Resolved in version `0.28.3`
